module.exports = {
  apps: [
    {
      name: 'oxengl-api',
      script: 'services/apiService.cjs',
      cwd: '/root/oxen-gl',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '500M',
      restart_delay: 3000,
      env: {
        NODE_ENV: 'production',
        PORT: 8001,
      },
      out_file: '/root/oxen-gl/logs/oxengl-api.out.log',
      error_file: '/root/oxen-gl/logs/oxengl-api.err.log',
      merge_logs: true,
    },
    {
      name: 'oxengl-compliance-cron',
      script: 'services/complianceCron.cjs',
      cwd: '/root/oxen-gl',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '500M',
      restart_delay: 3000,
      env: {
        NODE_ENV: 'production',
      },
      out_file: '/root/oxen-gl/logs/compliance-cron.out.log',
      error_file: '/root/oxen-gl/logs/compliance-cron.err.log',
      merge_logs: true,
    },
    {
      name: 'oxengl-tcp-listener',
      script: 'services/teltonikaListener.cjs',
      cwd: '/root/oxen-gl',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '500M',
      restart_delay: 3000,
      env: {
        NODE_ENV: 'production',
        TCP_INGESTION_PORT: 13000,
      },
      out_file: '/root/oxen-gl/logs/tcp-listener.out.log',
      error_file: '/root/oxen-gl/logs/tcp-listener.err.log',
      merge_logs: true,
    },
    {
      name: 'oxengl-wasl-worker',
      script: 'workers/waslQueueWorker.cjs',
      cwd: '/root/oxen-gl',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '500M',
      restart_delay: 3000,
      env: {
        NODE_ENV: 'production',
      },
      out_file: '/root/oxen-gl/logs/wasl-worker.out.log',
      error_file: '/root/oxen-gl/logs/wasl-worker.err.log',
      merge_logs: true,
    },
  ],
};
