"""deploy_oxengl_phase4_logistics_core

Revision ID: 15b54a41af4d
Revises: 5dd4856b2520
Create Date: 2026-09-13 15:37:51.502262+00:00
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '15b54a41af4d'
down_revision: Union[str, None] = '5dd4856b2520'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery_manifests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('manifest_number', sa.String(length=100), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('driver_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('total_distance_km', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delivery_manifests_manifest_number'), 'delivery_manifests', ['manifest_number'], unique=True)
    op.create_index(op.f('ix_delivery_manifests_tenant_id'), 'delivery_manifests', ['tenant_id'], unique=False)
    op.create_table('iot_telemetry_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('cargo_temperature_celsius', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('ambient_humidity_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('device_battery_voltage', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_iot_telemetry_events_tenant_id'), 'iot_telemetry_events', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_iot_telemetry_events_timestamp'), 'iot_telemetry_events', ['timestamp'], unique=False)
    op.create_index(op.f('ix_iot_telemetry_events_vehicle_id'), 'iot_telemetry_events', ['vehicle_id'], unique=False)
    op.create_table('manifest_stops',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('manifest_id', sa.UUID(), nullable=False),
    sa.Column('waybill_id', sa.UUID(), nullable=False),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['manifest_id'], ['delivery_manifests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['waybill_id'], ['waybills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manifest_stops_manifest_id'), 'manifest_stops', ['manifest_id'], unique=False)
    op.create_index(op.f('ix_manifest_stops_waybill_id'), 'manifest_stops', ['waybill_id'], unique=False)
    op.create_index('uq_manifest_stops_waybill', 'manifest_stops', ['manifest_id', 'waybill_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_manifest_stops_waybill', table_name='manifest_stops')
    op.drop_index(op.f('ix_manifest_stops_waybill_id'), table_name='manifest_stops')
    op.drop_index(op.f('ix_manifest_stops_manifest_id'), table_name='manifest_stops')
    op.drop_table('manifest_stops')
    op.drop_index(op.f('ix_iot_telemetry_events_vehicle_id'), table_name='iot_telemetry_events')
    op.drop_index(op.f('ix_iot_telemetry_events_timestamp'), table_name='iot_telemetry_events')
    op.drop_index(op.f('ix_iot_telemetry_events_tenant_id'), table_name='iot_telemetry_events')
    op.drop_table('iot_telemetry_events')
    op.drop_index(op.f('ix_delivery_manifests_tenant_id'), table_name='delivery_manifests')
    op.drop_index(op.f('ix_delivery_manifests_manifest_number'), table_name='delivery_manifests')
    op.drop_table('delivery_manifests')
    # ### end Alembic commands ###
