"""deploy_oxengl_phase3_ai_vector_core

Revision ID: 5dd4856b2520
Revises: 1c817cc99a6f
Create Date: 2026-09-13 13:45:51.829706+00:00
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

revision: str = '5dd4856b2520'
down_revision: Union[str, None] = '1c817cc99a6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_knowledge_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_knowledge_documents_tenant_id'), 'ai_knowledge_documents', ['tenant_id'], unique=False)
    op.create_table('ai_knowledge_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['ai_knowledge_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_knowledge_chunks_tenant_id'), 'ai_knowledge_chunks', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_knowledge_chunks_tenant_id'), table_name='ai_knowledge_chunks')
    op.drop_table('ai_knowledge_chunks')
    op.drop_index(op.f('ix_ai_knowledge_documents_tenant_id'), table_name='ai_knowledge_documents')
    op.drop_table('ai_knowledge_documents')
    # ### end Alembic commands ###
