"""upgrade_oxengl_enterprise_platform_matrix

Revision ID: 6f0be22aa454
Revises: 202609060005
Create Date: 2026-09-12 18:37:58.666922+00:00
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '6f0be22aa454'
down_revision: Union[str, None] = '202609060005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('device_id', sa.String(length=255), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('failure_reason', sa.String(length=100), nullable=True),
    sa.Column('attempt_time', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_login_attempts_ip_address'), 'login_attempts', ['ip_address'], unique=False)
    op.create_index(op.f('ix_login_attempts_username'), 'login_attempts', ['username'], unique=False)
    op.create_table('saas_invoices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('invoice_number', sa.String(length=64), nullable=False),
    sa.Column('billing_cycle', sa.String(length=32), nullable=False),
    sa.Column('tier', sa.String(length=32), nullable=False),
    sa.Column('amount_sar', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('issued_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pdf_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("billing_cycle IN ('monthly', 'yearly', 'quarterly')", name='ck_saas_invoice_cycle'),
    sa.CheckConstraint("status IN ('paid', 'pending', 'overdue', 'cancelled')", name='ck_saas_invoice_status'),
    sa.ForeignKeyConstraint(['tenant_id'], ['master_tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saas_invoices_invoice_number'), 'saas_invoices', ['invoice_number'], unique=True)
    op.create_index(op.f('ix_saas_invoices_tenant_id'), 'saas_invoices', ['tenant_id'], unique=False)
    op.create_table('security_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_type', sa.String(length=50), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['res_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_tokens_token_hash'), 'security_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_security_tokens_user_id'), 'security_tokens', ['user_id'], unique=False)
    op.create_table('user_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('device_name', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('logged_in_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['res_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_sessions_tenant_id'), 'user_sessions', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.create_table('fleet_trips',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('trip_number', sa.String(length=64), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=True),
    sa.Column('driver_id', sa.UUID(), nullable=True),
    sa.Column('origin_location', sa.String(length=255), nullable=False),
    sa.Column('destination_location', sa.String(length=255), nullable=False),
    sa.Column('cargo_description', sa.String(length=255), nullable=True),
    sa.Column('planned_weight_tons', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('scheduled_departure', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_departure', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_delivery', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_latitude', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('current_longitude', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('speed_kmh', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('last_gps_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('assigned', 'in_transit', 'en_route_pickup', 'at_pickup', 'loaded', 'en_route_delivery', 'at_delivery', 'delivered', 'cancelled')", name='ck_fleet_trip_status'),
    sa.ForeignKeyConstraint(['company_id'], ['res_companies.id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['res_partners.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fleet_trips_company_id'), 'fleet_trips', ['company_id'], unique=False)
    op.create_index(op.f('ix_fleet_trips_driver_id'), 'fleet_trips', ['driver_id'], unique=False)
    op.create_index('ix_fleet_trips_status', 'fleet_trips', ['company_id', 'status'], unique=False)
    op.create_index(op.f('ix_fleet_trips_trip_number'), 'fleet_trips', ['trip_number'], unique=False)
    op.create_index(op.f('ix_fleet_trips_vehicle_id'), 'fleet_trips', ['vehicle_id'], unique=False)
    op.create_index('uq_fleet_trips_company_number', 'fleet_trips', ['company_id', 'trip_number'], unique=True)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_reason', sa.String(length=100), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['user_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_session_id'), 'refresh_tokens', ['session_id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('delivery_proofs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('recipient_name', sa.String(length=128), nullable=False),
    sa.Column('recipient_phone', sa.String(length=32), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('altitude', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('accuracy_meters', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('digital_signature_data', sa.Text(), nullable=True),
    sa.Column('encrypted_photo_urls', sa.Text(), nullable=True),
    sa.Column('delivery_notes', sa.Text(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['res_companies.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['fleet_trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delivery_proofs_company_id'), 'delivery_proofs', ['company_id'], unique=False)
    op.create_index(op.f('ix_delivery_proofs_trip_id'), 'delivery_proofs', ['trip_id'], unique=True)
    op.create_table('trip_inspection_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=True),
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('driver_id', sa.UUID(), nullable=True),
    sa.Column('inspection_type', sa.String(length=32), nullable=False),
    sa.Column('odometer_reading', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('is_safe_to_operate', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('inspected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("inspection_type IN ('pre_trip', 'post_trip', 'safety_audit')", name='ck_trip_inspection_type'),
    sa.ForeignKeyConstraint(['company_id'], ['res_companies.id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['res_partners.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trip_id'], ['fleet_trips.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trip_inspection_logs_company_id'), 'trip_inspection_logs', ['company_id'], unique=False)
    op.create_index(op.f('ix_trip_inspection_logs_driver_id'), 'trip_inspection_logs', ['driver_id'], unique=False)
    op.create_index(op.f('ix_trip_inspection_logs_trip_id'), 'trip_inspection_logs', ['trip_id'], unique=False)
    op.create_index(op.f('ix_trip_inspection_logs_vehicle_id'), 'trip_inspection_logs', ['vehicle_id'], unique=False)
    op.add_column('fuel_transactions', sa.Column('trip_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_fuel_transactions_trip_id'), 'fuel_transactions', ['trip_id'], unique=False)
    op.create_foreign_key(None, 'fuel_transactions', 'fleet_trips', ['trip_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_master_password_resets_token'), table_name='master_password_resets')
    op.drop_constraint(op.f('master_password_resets_reset_token_key'), 'master_password_resets', type_='unique')
    op.create_index(op.f('ix_master_password_resets_reset_token'), 'master_password_resets', ['reset_token'], unique=True)
    op.add_column('master_tenants', sa.Column('max_storage_gb', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_master_tenants_domain'), table_name='master_tenants')
    op.drop_constraint(op.f('master_tenants_custom_domain_key'), 'master_tenants', type_='unique')
    op.drop_constraint(op.f('master_tenants_slug_key'), 'master_tenants', type_='unique')
    op.drop_index(op.f('ix_master_tenants_slug'), table_name='master_tenants')
    op.create_index(op.f('ix_master_tenants_slug'), 'master_tenants', ['slug'], unique=True)
    op.create_index(op.f('ix_master_tenants_custom_domain'), 'master_tenants', ['custom_domain'], unique=True)
    op.drop_index(op.f('ix_master_users_mobile'), table_name='master_users')
    op.drop_constraint(op.f('master_users_email_key'), 'master_users', type_='unique')
    op.drop_constraint(op.f('master_users_mobile_number_key'), 'master_users', type_='unique')
    op.drop_index(op.f('ix_master_users_email'), table_name='master_users')
    op.create_index(op.f('ix_master_users_email'), 'master_users', ['email'], unique=True)
    op.create_index(op.f('ix_master_users_mobile_number'), 'master_users', ['mobile_number'], unique=True)
    op.drop_constraint(op.f('res_companies_slug_key'), 'res_companies', type_='unique')
    op.drop_index(op.f('ix_res_companies_slug'), table_name='res_companies')
    op.create_index(op.f('ix_res_companies_slug'), 'res_companies', ['slug'], unique=True)
    op.drop_column('res_companies', 'ui_secondary_color')
    op.add_column('res_users', sa.Column('mfa_enabled', sa.Boolean(), nullable=False))
    op.add_column('res_users', sa.Column('mfa_secret', sa.String(length=255), nullable=True))
    op.add_column('res_users', sa.Column('mfa_backup_codes', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_constraint(op.f('res_users_email_key'), 'res_users', type_='unique')
    op.drop_constraint(op.f('res_users_firebase_uid_key'), 'res_users', type_='unique')
    op.drop_index(op.f('ix_res_users_email'), table_name='res_users')
    op.create_index(op.f('ix_res_users_email'), 'res_users', ['email'], unique=True)
    op.drop_index(op.f('ix_res_users_firebase_uid'), table_name='res_users')
    op.create_index(op.f('ix_res_users_firebase_uid'), 'res_users', ['firebase_uid'], unique=True)
    op.drop_index(op.f('ix_stock_moves_picking_id'), table_name='stock_moves')
    op.drop_index(op.f('ix_tenant_password_resets_token'), table_name='tenant_password_resets')
    op.drop_constraint(op.f('tenant_password_resets_reset_token_key'), 'tenant_password_resets', type_='unique')
    op.create_index(op.f('ix_tenant_password_resets_reset_token'), 'tenant_password_resets', ['reset_token'], unique=True)
    op.drop_index(op.f('ix_tenant_user_invitations_token'), table_name='tenant_user_invitations')
    op.drop_constraint(op.f('tenant_user_invitations_invite_token_key'), 'tenant_user_invitations', type_='unique')
    op.create_index(op.f('ix_tenant_user_invitations_invite_token'), 'tenant_user_invitations', ['invite_token'], unique=True)
    op.drop_index(op.f('ix_tenant_users_mobile'), table_name='tenant_users')
    op.drop_constraint(op.f('tenant_users_email_key'), 'tenant_users', type_='unique')
    op.drop_constraint(op.f('tenant_users_mobile_number_key'), 'tenant_users', type_='unique')
    op.drop_index(op.f('ix_tenant_users_email'), table_name='tenant_users')
    op.create_index(op.f('ix_tenant_users_email'), 'tenant_users', ['email'], unique=True)
    op.create_index(op.f('ix_tenant_users_mobile_number'), 'tenant_users', ['mobile_number'], unique=True)
    op.create_index(op.f('ix_tenant_users_role'), 'tenant_users', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenant_users_role'), table_name='tenant_users')
    op.drop_index(op.f('ix_tenant_users_mobile_number'), table_name='tenant_users')
    op.drop_index(op.f('ix_tenant_users_email'), table_name='tenant_users')
    op.create_index(op.f('ix_tenant_users_email'), 'tenant_users', ['email'], unique=False)
    op.create_unique_constraint(op.f('tenant_users_mobile_number_key'), 'tenant_users', ['mobile_number'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('tenant_users_email_key'), 'tenant_users', ['email'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_tenant_users_mobile'), 'tenant_users', ['mobile_number'], unique=False)
    op.drop_index(op.f('ix_tenant_user_invitations_invite_token'), table_name='tenant_user_invitations')
    op.create_unique_constraint(op.f('tenant_user_invitations_invite_token_key'), 'tenant_user_invitations', ['invite_token'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_tenant_user_invitations_token'), 'tenant_user_invitations', ['invite_token'], unique=False)
    op.drop_index(op.f('ix_tenant_password_resets_reset_token'), table_name='tenant_password_resets')
    op.create_unique_constraint(op.f('tenant_password_resets_reset_token_key'), 'tenant_password_resets', ['reset_token'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_tenant_password_resets_token'), 'tenant_password_resets', ['reset_token'], unique=False)
    op.create_index(op.f('ix_stock_moves_picking_id'), 'stock_moves', ['picking_id'], unique=False)
    op.drop_index(op.f('ix_res_users_firebase_uid'), table_name='res_users')
    op.create_index(op.f('ix_res_users_firebase_uid'), 'res_users', ['firebase_uid'], unique=False)
    op.drop_index(op.f('ix_res_users_email'), table_name='res_users')
    op.create_index(op.f('ix_res_users_email'), 'res_users', ['email'], unique=False)
    op.create_unique_constraint(op.f('res_users_firebase_uid_key'), 'res_users', ['firebase_uid'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('res_users_email_key'), 'res_users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_column('res_users', 'mfa_backup_codes')
    op.drop_column('res_users', 'mfa_secret')
    op.drop_column('res_users', 'mfa_enabled')
    op.add_column('res_companies', sa.Column('ui_secondary_color', sa.VARCHAR(length=9), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_res_companies_slug'), table_name='res_companies')
    op.create_index(op.f('ix_res_companies_slug'), 'res_companies', ['slug'], unique=False)
    op.create_unique_constraint(op.f('res_companies_slug_key'), 'res_companies', ['slug'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_master_users_mobile_number'), table_name='master_users')
    op.drop_index(op.f('ix_master_users_email'), table_name='master_users')
    op.create_index(op.f('ix_master_users_email'), 'master_users', ['email'], unique=False)
    op.create_unique_constraint(op.f('master_users_mobile_number_key'), 'master_users', ['mobile_number'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('master_users_email_key'), 'master_users', ['email'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_master_users_mobile'), 'master_users', ['mobile_number'], unique=False)
    op.drop_index(op.f('ix_master_tenants_custom_domain'), table_name='master_tenants')
    op.drop_index(op.f('ix_master_tenants_slug'), table_name='master_tenants')
    op.create_index(op.f('ix_master_tenants_slug'), 'master_tenants', ['slug'], unique=False)
    op.create_unique_constraint(op.f('master_tenants_slug_key'), 'master_tenants', ['slug'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('master_tenants_custom_domain_key'), 'master_tenants', ['custom_domain'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_master_tenants_domain'), 'master_tenants', ['custom_domain'], unique=False)
    op.drop_column('master_tenants', 'max_storage_gb')
    op.drop_index(op.f('ix_master_password_resets_reset_token'), table_name='master_password_resets')
    op.create_unique_constraint(op.f('master_password_resets_reset_token_key'), 'master_password_resets', ['reset_token'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_master_password_resets_token'), 'master_password_resets', ['reset_token'], unique=False)
    op.drop_constraint(None, 'fuel_transactions', type_='foreignkey')
    op.drop_index(op.f('ix_fuel_transactions_trip_id'), table_name='fuel_transactions')
    op.drop_column('fuel_transactions', 'trip_id')
    op.drop_index(op.f('ix_trip_inspection_logs_vehicle_id'), table_name='trip_inspection_logs')
    op.drop_index(op.f('ix_trip_inspection_logs_trip_id'), table_name='trip_inspection_logs')
    op.drop_index(op.f('ix_trip_inspection_logs_driver_id'), table_name='trip_inspection_logs')
    op.drop_index(op.f('ix_trip_inspection_logs_company_id'), table_name='trip_inspection_logs')
    op.drop_table('trip_inspection_logs')
    op.drop_index(op.f('ix_delivery_proofs_trip_id'), table_name='delivery_proofs')
    op.drop_index(op.f('ix_delivery_proofs_company_id'), table_name='delivery_proofs')
    op.drop_table('delivery_proofs')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_session_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index('uq_fleet_trips_company_number', table_name='fleet_trips')
    op.drop_index(op.f('ix_fleet_trips_vehicle_id'), table_name='fleet_trips')
    op.drop_index(op.f('ix_fleet_trips_trip_number'), table_name='fleet_trips')
    op.drop_index('ix_fleet_trips_status', table_name='fleet_trips')
    op.drop_index(op.f('ix_fleet_trips_driver_id'), table_name='fleet_trips')
    op.drop_index(op.f('ix_fleet_trips_company_id'), table_name='fleet_trips')
    op.drop_table('fleet_trips')
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_tenant_id'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_security_tokens_user_id'), table_name='security_tokens')
    op.drop_index(op.f('ix_security_tokens_token_hash'), table_name='security_tokens')
    op.drop_table('security_tokens')
    op.drop_index(op.f('ix_saas_invoices_tenant_id'), table_name='saas_invoices')
    op.drop_index(op.f('ix_saas_invoices_invoice_number'), table_name='saas_invoices')
    op.drop_table('saas_invoices')
    op.drop_index(op.f('ix_login_attempts_username'), table_name='login_attempts')
    op.drop_index(op.f('ix_login_attempts_ip_address'), table_name='login_attempts')
    op.drop_table('login_attempts')
    # ### end Alembic commands ###
