"""deploy_oxengl_phase2_hr_payroll_core

Revision ID: b20551fbfd86
Revises: 6f0be22aa454
Create Date: 2026-09-13 12:25:24.356572+00:00
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import backend.app.domains.finance.models

revision: str = 'b20551fbfd86'
down_revision: Union[str, None] = '6f0be22aa454'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('path', backend.app.domains.finance.models.LtreeType(), nullable=False),
    sa.Column('account_type', sa.String(length=50), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index('idx_accounts_code', 'accounts', ['code'], unique=False)
    op.create_index('idx_accounts_path_gist', 'accounts', ['path'], unique=False, postgresql_using='gist')
    op.create_index('idx_accounts_tenant_type', 'accounts', ['tenant_id', 'account_type'], unique=False)
    op.create_index(op.f('ix_accounts_company_id'), 'accounts', ['company_id'], unique=False)
    op.create_index(op.f('ix_accounts_tenant_id'), 'accounts', ['tenant_id'], unique=False)
    op.create_table('approval_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('cost_center_id', sa.UUID(), nullable=True),
    sa.Column('min_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('max_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('required_role_code', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_rules_cost_center_id'), 'approval_rules', ['cost_center_id'], unique=False)
    op.create_index(op.f('ix_approval_rules_tenant_id'), 'approval_rules', ['tenant_id'], unique=False)
    op.create_table('journal_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('entry_number', sa.String(length=64), nullable=False),
    sa.Column('entry_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('total_debit', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('total_credit', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('posted_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('total_debit = total_credit', name='ck_journal_entries_balanced'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entry_number')
    )
    op.create_index(op.f('ix_journal_entries_company_id'), 'journal_entries', ['company_id'], unique=False)
    op.create_index(op.f('ix_journal_entries_tenant_id'), 'journal_entries', ['tenant_id'], unique=False)
    op.create_table('materials',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('primary_uom', sa.String(length=20), nullable=False),
    sa.Column('secondary_uom', sa.String(length=20), nullable=True),
    sa.Column('uom_conversion_ratio', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('valuation_method', sa.String(length=30), nullable=False),
    sa.Column('standard_cost', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('current_moving_avg_cost', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('density_factor', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_materials_company_id'), 'materials', ['company_id'], unique=False)
    op.create_index(op.f('ix_materials_tenant_id'), 'materials', ['tenant_id'], unique=False)
    op.create_table('purchase_requisitions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('pr_number', sa.String(length=64), nullable=False),
    sa.Column('requester_id', sa.UUID(), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('cost_center_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('justification', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('total_estimated_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pr_number')
    )
    op.create_index(op.f('ix_purchase_requisitions_requester_id'), 'purchase_requisitions', ['requester_id'], unique=False)
    op.create_index(op.f('ix_purchase_requisitions_tenant_id'), 'purchase_requisitions', ['tenant_id'], unique=False)
    op.create_table('vendors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('vendor_code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('commercial_registration', sa.String(length=64), nullable=True),
    sa.Column('vat_number', sa.String(length=64), nullable=True),
    sa.Column('payment_terms_days', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vendor_code')
    )
    op.create_index(op.f('ix_vendors_tenant_id'), 'vendors', ['tenant_id'], unique=False)
    op.create_table('workflow_instances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('current_step', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_instances_document_id'), 'workflow_instances', ['document_id'], unique=False)
    op.create_index(op.f('ix_workflow_instances_tenant_id'), 'workflow_instances', ['tenant_id'], unique=False)
    op.create_table('journal_lines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entry_id', sa.UUID(), nullable=False),
    sa.Column('account_code', sa.String(length=50), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=True),
    sa.Column('debit', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('credit', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('cost_center_id', sa.UUID(), nullable=True),
    sa.CheckConstraint('(debit > 0 AND credit = 0) OR (credit > 0 AND debit = 0)', name='ck_journal_lines_either_dr_cr'),
    sa.CheckConstraint('debit >= 0 AND credit >= 0', name='ck_journal_lines_non_negative'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['entry_id'], ['journal_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journal_lines_account_code'), 'journal_lines', ['account_code'], unique=False)
    op.create_index(op.f('ix_journal_lines_entry_id'), 'journal_lines', ['entry_id'], unique=False)
    op.create_table('purchase_requisition_lines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('requisition_id', sa.UUID(), nullable=False),
    sa.Column('item_description', sa.String(length=255), nullable=False),
    sa.Column('material_id', sa.UUID(), nullable=True),
    sa.Column('quantity_requested', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('uom', sa.String(length=20), nullable=False),
    sa.Column('estimated_unit_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['requisition_id'], ['purchase_requisitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_requisition_lines_requisition_id'), 'purchase_requisition_lines', ['requisition_id'], unique=False)
    op.create_table('stock_balances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('material_id', sa.UUID(), nullable=False),
    sa.Column('quantity_on_hand', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('quantity_reserved', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('quantity_available', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('unit_cost_moving_avg', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('total_valuation', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('last_revaluation_date', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_balances_material_id'), 'stock_balances', ['material_id'], unique=False)
    op.create_index(op.f('ix_stock_balances_tenant_id'), 'stock_balances', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_stock_balances_warehouse_id'), 'stock_balances', ['warehouse_id'], unique=False)
    op.create_index('uq_stock_balances_wh_material', 'stock_balances', ['warehouse_id', 'material_id'], unique=True)
    op.create_table('workflow_steps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('instance_id', sa.UUID(), nullable=False),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('assigned_role_code', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('actioned_by', sa.UUID(), nullable=True),
    sa.Column('actioned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['instance_id'], ['workflow_instances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_steps_instance_id'), 'workflow_steps', ['instance_id'], unique=False)
    op.create_table('drivers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('license_number', sa.String(length=100), nullable=False),
    sa.Column('license_type', sa.String(length=50), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['res_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('license_number')
    )
    op.create_index(op.f('ix_drivers_tenant_id'), 'drivers', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_drivers_user_id'), 'drivers', ['user_id'], unique=False)
    op.create_table('employees',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('employee_code', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('base_salary', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('hire_date', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['res_users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employees_department'), 'employees', ['department'], unique=False)
    op.create_index(op.f('ix_employees_employee_code'), 'employees', ['employee_code'], unique=True)
    op.create_index(op.f('ix_employees_tenant_id'), 'employees', ['tenant_id'], unique=False)
    op.create_table('attendance_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('check_in', sa.DateTime(timezone=True), nullable=False),
    sa.Column('check_out', sa.DateTime(timezone=True), nullable=True),
    sa.Column('device_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_logs_employee_id'), 'attendance_logs', ['employee_id'], unique=False)
    op.create_index(op.f('ix_attendance_logs_tenant_id'), 'attendance_logs', ['tenant_id'], unique=False)
    op.create_table('gps_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('speed_kph', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gps_events_tenant_id'), 'gps_events', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_gps_events_timestamp'), 'gps_events', ['timestamp'], unique=False)
    op.create_index(op.f('ix_gps_events_trip_id'), 'gps_events', ['trip_id'], unique=False)
    op.create_index(op.f('ix_gps_events_vehicle_id'), 'gps_events', ['vehicle_id'], unique=False)
    op.create_table('payroll_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('pay_period', sa.String(length=7), nullable=False),
    sa.Column('gross_earnings', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('allowances', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('deductions', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('net_pay', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payroll_runs_employee_id'), 'payroll_runs', ['employee_id'], unique=False)
    op.create_index(op.f('ix_payroll_runs_pay_period'), 'payroll_runs', ['pay_period'], unique=False)
    op.create_index(op.f('ix_payroll_runs_tenant_id'), 'payroll_runs', ['tenant_id'], unique=False)
    op.create_table('purchase_order_lines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('purchase_order_id', sa.UUID(), nullable=False),
    sa.Column('material_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('quantity_ordered', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('quantity_received', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('quantity_billed', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('line_subtotal', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_order_lines_material_id'), 'purchase_order_lines', ['material_id'], unique=False)
    op.create_index(op.f('ix_purchase_order_lines_purchase_order_id'), 'purchase_order_lines', ['purchase_order_id'], unique=False)
    op.create_table('waybills',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('waybill_number', sa.String(length=100), nullable=False),
    sa.Column('purchase_order_id', sa.UUID(), nullable=True),
    sa.Column('origin_warehouse_id', sa.UUID(), nullable=False),
    sa.Column('destination_warehouse_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('cargo_weight_ton', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_waybills_destination_warehouse_id'), 'waybills', ['destination_warehouse_id'], unique=False)
    op.create_index(op.f('ix_waybills_origin_warehouse_id'), 'waybills', ['origin_warehouse_id'], unique=False)
    op.create_index(op.f('ix_waybills_purchase_order_id'), 'waybills', ['purchase_order_id'], unique=False)
    op.create_index(op.f('ix_waybills_tenant_id'), 'waybills', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_waybills_waybill_number'), 'waybills', ['waybill_number'], unique=True)
    op.create_table('goods_receipt_batch_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('goods_receipt_id', sa.UUID(), nullable=False),
    sa.Column('material_id', sa.UUID(), nullable=True),
    sa.Column('batch_number', sa.String(length=64), nullable=False),
    sa.Column('quantity_received', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('uom', sa.String(length=20), nullable=False),
    sa.Column('manufacture_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expiry_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('inspection_result', sa.String(length=32), nullable=False),
    sa.Column('storage_location', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['goods_receipt_id'], ['goods_receipts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goods_receipt_batch_logs_batch_number'), 'goods_receipt_batch_logs', ['batch_number'], unique=False)
    op.create_index(op.f('ix_goods_receipt_batch_logs_goods_receipt_id'), 'goods_receipt_batch_logs', ['goods_receipt_id'], unique=False)
    op.create_index(op.f('ix_goods_receipt_batch_logs_material_id'), 'goods_receipt_batch_logs', ['material_id'], unique=False)
    op.create_table('landed_cost_allocations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('goods_receipt_id', sa.UUID(), nullable=False),
    sa.Column('freight_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('customs_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('port_handling_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('insurance_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('total_landed_cost', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('allocation_method', sa.String(length=30), nullable=False),
    sa.Column('is_posted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['goods_receipt_id'], ['goods_receipts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_landed_cost_allocations_goods_receipt_id'), 'landed_cost_allocations', ['goods_receipt_id'], unique=False)
    op.create_index(op.f('ix_landed_cost_allocations_tenant_id'), 'landed_cost_allocations', ['tenant_id'], unique=False)
    op.create_table('vendor_bills',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('invoice_number', sa.String(length=64), nullable=False),
    sa.Column('vendor_id', sa.UUID(), nullable=True),
    sa.Column('purchase_order_id', sa.UUID(), nullable=False),
    sa.Column('goods_receipt_id', sa.UUID(), nullable=False),
    sa.Column('invoice_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('total_billed', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('match_status', sa.String(length=32), nullable=False),
    sa.Column('discrepancy_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_posted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['goods_receipt_id'], ['goods_receipts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendor_bills_company_id'), 'vendor_bills', ['company_id'], unique=False)
    op.create_index(op.f('ix_vendor_bills_goods_receipt_id'), 'vendor_bills', ['goods_receipt_id'], unique=False)
    op.create_index(op.f('ix_vendor_bills_invoice_number'), 'vendor_bills', ['invoice_number'], unique=False)
    op.create_index(op.f('ix_vendor_bills_purchase_order_id'), 'vendor_bills', ['purchase_order_id'], unique=False)
    op.create_index(op.f('ix_vendor_bills_tenant_id'), 'vendor_bills', ['tenant_id'], unique=False)
    op.create_table('landed_cost_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('allocation_id', sa.UUID(), nullable=False),
    sa.Column('material_id', sa.UUID(), nullable=False),
    sa.Column('base_cost', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('allocated_expense', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('final_effective_cost', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['allocation_id'], ['landed_cost_allocations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_landed_cost_items_allocation_id'), 'landed_cost_items', ['allocation_id'], unique=False)
    op.add_column('vehicles', sa.Column('tenant_id', sa.UUID(), nullable=True))
    op.add_column('vehicles', sa.Column('plate_number', sa.String(length=50), nullable=True))
    op.add_column('vehicles', sa.Column('breakdown_risk_score', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_vehicles_plate_number'), 'vehicles', ['plate_number'], unique=False)
    op.create_index(op.f('ix_vehicles_tenant_id'), 'vehicles', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehicles_tenant_id'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_plate_number'), table_name='vehicles')
    op.drop_column('vehicles', 'breakdown_risk_score')
    op.drop_column('vehicles', 'plate_number')
    op.drop_column('vehicles', 'tenant_id')
    op.drop_index(op.f('ix_landed_cost_items_allocation_id'), table_name='landed_cost_items')
    op.drop_table('landed_cost_items')
    op.drop_index(op.f('ix_vendor_bills_tenant_id'), table_name='vendor_bills')
    op.drop_index(op.f('ix_vendor_bills_purchase_order_id'), table_name='vendor_bills')
    op.drop_index(op.f('ix_vendor_bills_invoice_number'), table_name='vendor_bills')
    op.drop_index(op.f('ix_vendor_bills_goods_receipt_id'), table_name='vendor_bills')
    op.drop_index(op.f('ix_vendor_bills_company_id'), table_name='vendor_bills')
    op.drop_table('vendor_bills')
    op.drop_index(op.f('ix_landed_cost_allocations_tenant_id'), table_name='landed_cost_allocations')
    op.drop_index(op.f('ix_landed_cost_allocations_goods_receipt_id'), table_name='landed_cost_allocations')
    op.drop_table('landed_cost_allocations')
    op.drop_index(op.f('ix_goods_receipt_batch_logs_material_id'), table_name='goods_receipt_batch_logs')
    op.drop_index(op.f('ix_goods_receipt_batch_logs_goods_receipt_id'), table_name='goods_receipt_batch_logs')
    op.drop_index(op.f('ix_goods_receipt_batch_logs_batch_number'), table_name='goods_receipt_batch_logs')
    op.drop_table('goods_receipt_batch_logs')
    op.drop_index(op.f('ix_waybills_waybill_number'), table_name='waybills')
    op.drop_index(op.f('ix_waybills_tenant_id'), table_name='waybills')
    op.drop_index(op.f('ix_waybills_purchase_order_id'), table_name='waybills')
    op.drop_index(op.f('ix_waybills_origin_warehouse_id'), table_name='waybills')
    op.drop_index(op.f('ix_waybills_destination_warehouse_id'), table_name='waybills')
    op.drop_table('waybills')
    op.drop_index(op.f('ix_purchase_order_lines_purchase_order_id'), table_name='purchase_order_lines')
    op.drop_index(op.f('ix_purchase_order_lines_material_id'), table_name='purchase_order_lines')
    op.drop_table('purchase_order_lines')
    op.drop_index(op.f('ix_payroll_runs_tenant_id'), table_name='payroll_runs')
    op.drop_index(op.f('ix_payroll_runs_pay_period'), table_name='payroll_runs')
    op.drop_index(op.f('ix_payroll_runs_employee_id'), table_name='payroll_runs')
    op.drop_table('payroll_runs')
    op.drop_index(op.f('ix_gps_events_vehicle_id'), table_name='gps_events')
    op.drop_index(op.f('ix_gps_events_trip_id'), table_name='gps_events')
    op.drop_index(op.f('ix_gps_events_timestamp'), table_name='gps_events')
    op.drop_index(op.f('ix_gps_events_tenant_id'), table_name='gps_events')
    op.drop_table('gps_events')
    op.drop_index(op.f('ix_attendance_logs_tenant_id'), table_name='attendance_logs')
    op.drop_index(op.f('ix_attendance_logs_employee_id'), table_name='attendance_logs')
    op.drop_table('attendance_logs')
    op.drop_index(op.f('ix_employees_tenant_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_employee_code'), table_name='employees')
    op.drop_index(op.f('ix_employees_department'), table_name='employees')
    op.drop_table('employees')
    op.drop_index(op.f('ix_drivers_user_id'), table_name='drivers')
    op.drop_index(op.f('ix_drivers_tenant_id'), table_name='drivers')
    op.drop_table('drivers')
    op.drop_index(op.f('ix_workflow_steps_instance_id'), table_name='workflow_steps')
    op.drop_table('workflow_steps')
    op.drop_index('uq_stock_balances_wh_material', table_name='stock_balances')
    op.drop_index(op.f('ix_stock_balances_warehouse_id'), table_name='stock_balances')
    op.drop_index(op.f('ix_stock_balances_tenant_id'), table_name='stock_balances')
    op.drop_index(op.f('ix_stock_balances_material_id'), table_name='stock_balances')
    op.drop_table('stock_balances')
    op.drop_index(op.f('ix_purchase_requisition_lines_requisition_id'), table_name='purchase_requisition_lines')
    op.drop_table('purchase_requisition_lines')
    op.drop_index(op.f('ix_journal_lines_entry_id'), table_name='journal_lines')
    op.drop_index(op.f('ix_journal_lines_account_code'), table_name='journal_lines')
    op.drop_table('journal_lines')
    op.drop_index(op.f('ix_workflow_instances_tenant_id'), table_name='workflow_instances')
    op.drop_index(op.f('ix_workflow_instances_document_id'), table_name='workflow_instances')
    op.drop_table('workflow_instances')
    op.drop_index(op.f('ix_vendors_tenant_id'), table_name='vendors')
    op.drop_table('vendors')
    op.drop_index(op.f('ix_purchase_requisitions_tenant_id'), table_name='purchase_requisitions')
    op.drop_index(op.f('ix_purchase_requisitions_requester_id'), table_name='purchase_requisitions')
    op.drop_table('purchase_requisitions')
    op.drop_index(op.f('ix_materials_tenant_id'), table_name='materials')
    op.drop_index(op.f('ix_materials_company_id'), table_name='materials')
    op.drop_table('materials')
    op.drop_index(op.f('ix_journal_entries_tenant_id'), table_name='journal_entries')
    op.drop_index(op.f('ix_journal_entries_company_id'), table_name='journal_entries')
    op.drop_table('journal_entries')
    op.drop_index(op.f('ix_approval_rules_tenant_id'), table_name='approval_rules')
    op.drop_index(op.f('ix_approval_rules_cost_center_id'), table_name='approval_rules')
    op.drop_table('approval_rules')
    op.drop_index(op.f('ix_accounts_tenant_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_company_id'), table_name='accounts')
    op.drop_index('idx_accounts_tenant_type', table_name='accounts')
    op.drop_index('idx_accounts_path_gist', table_name='accounts', postgresql_using='gist')
    op.drop_index('idx_accounts_code', table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
